apiVersion: v1
kind: Pod
metadata:
  name: io-benchmark-pod
  labels:
    app: io-benchmark
    owner: rotemshavitt
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: python-benchmarking
    image: pytorch/pytorch:latest 
    command:
    - "/bin/bash"
    - "-c"
    - |
      apt-get update && \
      apt-get install -y build-essential && \
      pip install ninja aiofiles nixl && \
      sleep infinity
    resources:
      requests:
        memory: "300Gi"
        cpu: "12"
        nvidia.com/gpu: "1"
      limits:
        memory: "300Gi"
        cpu: "128"
        nvidia.com/gpu: "1"
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: "200Gi" # Adjust based on 'buffer_size' variable