apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-benchmark-pvc
  labels:
    app: io-benchmark
    owner: rotemshavitt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi

