apiVersion: v1
kind: Pod
metadata:
  name: io-benchmark-pod
  labels:
    app: io-benchmark
    owner: rotemshavitt
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: python-benchmarking
    image: pytorch/pytorch:latest 
    command:
    - "/bin/bash"
    - "-c"
    - |
      apt-get update && \
      apt-get install -y build-essential && \
      pip install ninja aiofiles nixl && \
      sleep infinity
    env:
    - name: STORAGE_PATH
      value: "/mnt/persistent-storage"  # Change to "/mnt/persistent-storage" for real storage testing
    - name: CLUSTER_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['cluster']
    resources:
      requests:
        memory: "300Gi"
        cpu: "12"
        nvidia.com/gpu: "1"
      limits:
        memory: "300Gi"
        cpu: "128"
        nvidia.com/gpu: "1"
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /mnt/persistent-storage
      name: persistent-storage
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: "300Gi" # Adjust based on 'buffer_size' variable
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: io-benchmark-pvc